# Generated by Django 4.2.6 on 2023-10-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
